### ISSUE TITLE
Llamada a chartJSON

### ISSUE THREAD

**Issue by giovas94** [bitsoex/front-end-challenge#1]
No se puede ejecutar la consulta a:
https://bitso.com/trade/chartJSON/btc_mxn/1month 
desde el localhost para realizar pruebas.

<img width="565" alt="captura de pantalla 2018-05-14 a la s 15 47 03" src="https://user-images.githubusercontent.com/11933312/40022673-50a7d90e-578e-11e8-982b-57d5e0ce7114.png">

**Comment by lito0** [comment]
Hey @giovas94, para fines de prueba, trata de deshabilitar same origin policy en tu navegador. Búscalo esa opción en las configuraciones avanzadas. También hay plugins también para hacer eso. Saludos.
