### ISSUE TITLE
No todos los endpoints de la API son amigables con CORS

### ISSUE THREAD

**Issue by pateketrueke** [bitsoex/front-end-challenge#14]
Hola, algunos endpoints de la API no funcionan con `fetch()`, pero algunos otros sí:

```js
fetch('https://api.bitso.com/v3/order_book?book=btc_mxn').then(console.log); // OK
fetch('https://api.bitso.com/v3/ticker?book=btc_mxn').then(console.log); // ERR
```

Captura:

![captura de pantalla 2018-05-28 a la s 11 52 36](https://user-images.githubusercontent.com/206371/40623685-b17a561e-626d-11e8-9533-7aa94b88d44f.png)

**Comment by vogelito** [comment]
Hola - checa las respuestas aquí: #1

**Comment by pateketrueke** [comment]
Hola @vogelito, gracias por le feedback.

Pero igual ando probando en Firefox y ocurre igual.

¿No es anormal que unos endpoints sean `cors-friendly` y otros no?

**Comment by loama** [comment]
Hola @pateketrueke, checa mi respuesta en #4, hice endpoints intermediarios para que los puedas consumir sin necesidad de el plugin de CORS.

**Comment by pateketrueke** [comment]
Está chido @loama, pero sí está troll _tener que_ depender de cosas intermedias para ésto; igual terminé haciendo mi propio proxy, porque igual está chistoso tener dos endpoints para consumir las APIs.

- http://bitso-api-v3.herokuapp.com/trade/chartJSON/btc_mxn
- http://bitso-api-v3.herokuapp.com/api/ticker?book=btc_mxn

**Comment by loama** [comment]
Pues supongo son endpoints planeados para uso interno, por eso no tienen cors.
Y el chiste es que sea un challenge, es para divertirse un rato 🏎 

Saludos y qué bueno que ya lo solucionaste.

**Comment by wemerald** [comment]
Exacto, los challenge son para divertirse, y llevarse la experiencia, si
fuera algo más formal ya sería proyecto vendido
😉
