### ISSUE TITLE
Push Denied

### ISSUE THREAD

**Issue by wemerald** [bitsoex/front-end-challenge#2]
![image](https://user-images.githubusercontent.com/35610263/40039825-882ba6fe-57dd-11e8-8ea2-739514c1f845.png)
Hola, me subir mis cambios, siempre obtengo un "Acces Denied", pueden orientarme por favor?

**Comment by vogelito** [comment]
Hola @wemerald - tienes que hacer un fork del repo y subir tu código al nuevo repo, no a este.

Saludos!

**Comment by vogelito** [comment]
Parece que ya hiciste el fork: https://github.com/wemerald/front-end-challenge

Tienes que cambiar tu remote a ese repo. Más info aquí: https://stackoverflow.com/questions/2432764/change-the-uri-url-for-a-remote-git-repository

**Comment by wemerald** [comment]
Muchas gracias Daniel, lo corroborare más tarde.

Agradezco el apoyo.

Saludos!
