### ISSUE TITLE
tick Ltc y bch

### ISSUE THREAD

**Issue by wemerald** [bitsoex/front-end-challenge#3]
Cuando consumo el servicio tick para LTC y BCH en ambiente Dev me tira un error:
https://api-dev.bitso.com/v3/ticker/?book=ltc_mxn
{"success":false,"error":{"code":"0301","message":"Unknown OrderBook ltc_mxn"}}

La misma petición en prod, es correcta, no hay inconveniente en apuntar a prod?
https://api.bitso.com/v3/ticker/?book=ltc_mxn
{"success":true,"payload":{"high":"2818.40","last":"2789.99","created_at":"2018-05-16T23:25:41+00:00","book":"ltc_mxn","volume":"738.62310167","vwap":"2749.56754780","low":"2720.01","ask":"2789.99","bid":"2740.00"}}

**Comment by loama** [comment]
No creo que haya problema con apuntar a prod, igual son puros GET

**Comment by vogelito** [comment]
Si - pueden apuntar a production. Gracias por checar!

**Comment by wemerald** [comment]
Gracias por la pronta respuesta, cerrado.
