### ISSUE TITLE
Ticker endpoint cross origin request blocked

### ISSUE THREAD

**Issue by QuarkTechnologies** [bitsoex/front-end-challenge#4]
Hola, tranajando con la API publica y recibo el siguiente error:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.bitso.com/v3/ticker/?book=btc_mx. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)`
Este error solo ocurre con la url:
` https://api.bitso.com/v3/ticker/?book=btc_mx'`
Las otras url funcionan bien, estoy usando axios, mi código luce:
`const url = 'https://api.bitso.com/v3/'
const tickerBtcMxn = () =>
  axios.get(url+'ticker/?book=btc_mx').then(res=>{
  console.log(data);
})`

El mismo código solo con diferente url funciona bien, ¿alguna idea?

**Comment by wemerald** [comment]
Hola amigo, debes instalar una extensión, revisa en el primer issue, ahí ponen el link a la extensión, con eso se soluciona

**Comment by loama** [comment]
ese endpoint no tiene habilitado [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).

Puedes instalar un plugin de tu navegador para desabilitar CORS en pruebas locales o puedes utilizar este endpoint que hice.

[bitso-challenge.firebaseapp.com/ticker?book=btc_mxn](bitso-challenge.firebaseapp.com/ticker?book=btc_mxn), funciona con cualquiera de los `books` disponibles

**Comment by QuarkTechnologies** [comment]
Excelente muchas gracias, cierro el issue

**Comment by ErnestoR** [comment]
@vogelito You should fix this! On both dev and Prod this is still and issue .... 🤦‍♂️

**Comment by ErnestoR** [comment]
@loama Gracias por ese intermediario!!

**Comment by vogelito** [comment]
@ErnestoR checa #1
