### ISSUE TITLE
Origin http://localhost:8080 is not allowed by Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by cesargdm** [bitsoex/front-end-challenge#5]
Cannot make GET request to https://api-dev.bitso.com/v3/ticker from localhost

**Comment by wemerald** [comment]
Hi cesar, you can check the first and four incident, an addon for chrome is
necesary to test that service

**Comment by vogelito** [comment]
@cesargdm - I recommend you use the production endpoint (https://api.bitso.com/v3/ticker) and check #1 to see how you can access the endpoints. I'm going to close this issue now.
